### ISSUE TITLE
'away' option: Does not seem to to work with Nest ECO mode

### ISSUE THREAD

**Issue by danielbrunt57** [ciotlosm/lovelace-thermostat-dark-card#264]
I am seeing a "Leaf" all the time.  I would presume the Leaf would only display when in 'ECO' mode?  I looked inside the code to determine how/when it displays the leaf and it looks like it is based on  'away' which is an internal boolean that is set based on the attribute I specified for the sensor but it presumes it will be either 'off' or 'on'??  I tried modifying the code to change 'on' to 'eco' but it made no difference...
```js
      if away_mode == 'eco' (
        away_mode = 'on'
      }
```
and also:
```yaml
away: (away_mode === 'on' || away_mode === 'eco'),
```
My Nest attributes:
```yaml
friendly_name: Living Room Nest Thermostat
entity_id: climate.living_room_nest_thermostat
unit_of_measure: °C
supported_features: 17
min_temp: 7
max_temp: 32
precision: 0.1
hvac_mode: heat
fan_mode: none
fan_timer_out: 'off'
preset_mode: ''
preset_modes:
  - eco
hvac_modes:
  - heat
  - 'off'
current_temperature: 21.8
current_humidty: 36
hvac_action: idle
temperature: 22
```

And in ECO mode:
```yaml
friendly_name: Living Room Nest Thermostat
entity_id: climate.living_room_nest_thermostat
unit_of_measure: °C
supported_features: 1
min_temp: 7
max_temp: 32
precision: 0.1
hvac_mode: heat
fan_mode: none
fan_timer_out: 'off'
preset_mode: eco
hvac_modes:
  - heat
  - 'off'
current_temperature: 21.8
current_humidty: 38
hvac_action: idle
target_temp_low: 16.1
target_temp_high: 24.4
```

My UI settings:
![thermostat-card](https://user-images.githubusercontent.com/49846893/98627355-e96d7380-22c8-11eb-92d2-14e4d4395b83.PNG)

In reality, the Nest displays a 'Leaf' regardless of ECO mode as long as the set temperature is at or below 18.5 C.
ECO mode is a separate function with presets akin to 'Away' mode with (in my case) Heat = 16 C and since it is below 18.5 triggers the Leaf.  The Eco Temperature  range setting in the Nest App displays a Leaf when the Eco Temperature is set slightly below 16.5 C...

**Comment by ciotlosm** [comment]
The bug is here: https://github.com/ciotlosm/custom-lovelace/blob/16f00b12a8eb8d5d6fd96f45a25f66baccbe7a37/thermostat-card/thermostat-card.js#L41

The states while fetching the correct away mode from a sensor, try to load it in the state, and on new hass states have it populated which is wrong.

**Comment by ciotlosm** [comment]
Could you try the new version with:

```yaml
away:
  sensor:
    state: 'eco'
```
