### ISSUE TITLE
Can we have transparent backround? 

### ISSUE THREAD

**Issue by sstefanowski** [ciotlosm/lovelace-thermostat-dark-card#268]
This thermostat looks awsome. I tried to use it but has minor issue - It's not a bug  - just useful extension maybe...

Can we have an option to make it "transparent" - just control to control opacity? 
I'm asking as I'm using picture backgrounds in my current thermostat controls (overriding background and unfortunately your control is not transparent and I cannot figure out which CSS to override :)

Please see the two attachemetns showing the options:
a) standard thermostat card (with overwritten CSS - background

b) your version without transparency
![StandardThermoWithTransparency](https://user-images.githubusercontent.com/36473471/100947260-98d2ea00-3505-11eb-8f82-2adb9bdf3679.png)
![DarkThermoWithoutTransparency](https://user-images.githubusercontent.com/36473471/100947241-89ec3780-3505-11eb-8fb3-b5960508ecb4.png)

I guess you know what I want to achieve :)

Maybe size control would be also nice-to-have not necessarily :)

Anyway, good job!

**Comment by ciotlosm** [comment]
Can you please post a sample config for your card setup so I can test when getting to implementing this?

**Comment by sstefanowski** [comment]
Sure....

Install card-mod from thomasloven and use "style" modificator.
BTW. To make your thermostat transparent I guess... just some CSS style need to be overriden (just like ha-card.background below), but I cannot figure out, what style is controling the circle. 
I tried to inspect using Chrome DevTools but I was unable to find it quickly - do you know? 

This is my config. I just changed the type of the card to your (custom:....).
```
    entity: climate.nnnnnnnnnnnn
    name: ' '
    style: |
      ha-card {
        background: url("/local/nnnnnnnn.jpg") center no-repeat;
      }
    theme: Dark - Blue/Purple
    type: thermostat
```
Also.... when I was inspecting CSS I think I found that background circle may change colors depending on the Thermostat state (on, off, heating, cooling) so when we have transparent background it would be nice to change the colors of the numbers or icons (instead of background).

**Comment by ciotlosm** [comment]
@sstefanowski the css is here: https://github.com/ciotlosm/lovelace-thermostat-dark-card/blob/master/src/thermostat-dark-card.ts#L184

You might try (until I get to testing) to redo:
```css
      ha-card svg.dial {
        --thermostat-off-fill: #555;
        --thermostat-idle-fill: #222;
        --thermostat-path-color: rgba(255, 255, 255, 0.3);
        --thermostat-heating-fill: #e36304;
        --thermostat-cooling-fill: #007af1;
        --thermostat-path-active-color: rgba(255, 255, 255, 0.8);
        --thermostat-path-active-color-large: rgba(255, 255, 255, 1);
        --thermostat-text-color: white;
      }
```

To achieve color on numbers & icons you might try: 

```css
   ha-card .dial--state--off .dial_ticks {
        fill: var(--thermostat-off-fill);
      }

   ha-card .dial--state--off .dial__lbl {
        fill: var(--thermostat-off-fill);
      }
```
