### ISSUE TITLE
Toggle state

### ISSUE THREAD

**Issue by kimme1024** [ciotlosm/lovelace-thermostat-dark-card#269]
**Is your feature request related to a problem? Please describe.**
As I'm using my thermostats manually from time to time, I toggle between `heat` and `off`. Somehow I can't find out how to get this option in this card.

**Describe the solution you'd like**
I'd like to be able to toggle between `heat` and `off` via this card.
It might also just be me who's overlooking something stupid... If so, feel free to make fun of it while giving me the solution ;)

**Describe alternatives you've considered**
/

**Additional context**
yaml:
```
type: 'custom:thermostat-dark-card'
entity: climate.lyric_c4dc2a
name: Woonkamer
step: '0.5'
chevron_size: '50'
hvac:
  states:
    'Off': 'off'
    Heating: heat
ambient_temperature: sensor.woonkamer_temperatuur
pending: '3'
idle_zone: '2'
highlight_tap: false
```

**Comment by fribse** [comment]
I'm trying to figure this out as well. I love the card's layout, very simple and square, perfect for a cellphone interface.
Our thermostats are shown like this in the developmenttools:
![image](https://user-images.githubusercontent.com/13660621/108612394-b3bc4880-73e8-11eb-9575-8bc6380767a8.png)
So I tried to make this config:
```
type: 'custom:thermostat-dark-card'
step: '0.5'
chevron_size: '50'
pending: '3'
idle_zone: '2'
entity: climate.thermostat_kitchen
hvac:
  states:
    'off': 'off'
    auto: auto
    heat: heat
  attribute: state
```
In the hopes it would show the state, but no, no state showing.
